name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      PYTHONPATH: "Scripts"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Source
        run: python -m Build R --copy

      - name: Ruleset
        run: python -m Build C Surge Ruleset --type --order

      - name: QuantumultX
        run: python -m Build C QuantumultX QuantumultX/Ruleset --type --order

      - name: Stash
        run: python -m Build C Stash Stash/Ruleset --type --order

      - name: Surge
        run: python -m Build C Surge Surge/Ruleset --type --order

      - name: Pycache
        run: find . -type d -name "__pycache__" -exec rm -rf {} +

      - name: Push Change
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git config --local user.name "${{ github.actor }}"
            git add -A
            git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
            git push origin master
          else
            echo "No Repository Update Detected."
          fi

      - name: Delete Workflow Run
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2